import Chat, { Conversation } from "@/components/chat/Chat";

export default function Chats() {
  const now = Date.now();

  const conversations: Conversation[] = [
    {
      conversationId: "c1",
      partnerId: "jane-doe",
      partnerFirstName: "Jane",
      partnerLastName: "Doe",
      partnerAvatarUrl: null,
      language: "English",
      lastMessageText: "Want to practice English today?",
      lastMessageAt: new Date(now - 3 * 60_000).toISOString(),
      unreadCount: 2,
      messages: [
        { id: "1", sender: "partner", text: "Hey!", sentAt: new Date(Date.now() - 1567 * 60_000).toISOString() },
        { id: "2", sender: "me", text: "Hi!", sentAt: new Date(Date.now() - 60 * 60_000).toISOString() },
        { id: "3", sender: "partner", text: "Can we practice our English?", sentAt: new Date(Date.now() - 32 * 60_000).toISOString() },
        { id: "4", sender: "me", text: "Yes.", sentAt: new Date(Date.now() - 16 * 60_000).toISOString() },
        { id: "5", sender: "me", text: "Where is the library?", sentAt: new Date(Date.now() - 16 * 60_000).toISOString() },
        { id: "6", sender: "partner", text: "The library is in the middle of the campus.", sentAt: new Date(Date.now() - 7 * 60_000).toISOString() },
        { id: "7", sender: "me", text: "I agree.", sentAt: new Date(Date.now() - 4 * 60_000).toISOString() },
        { id: "8", sender: "partner", text: "I am happy, because we share this feeling.", sentAt: new Date(Date.now() - 3 * 60_000).toISOString() },
        { id: "9", sender: "me", text: "What is your favorite food?", sentAt: new Date(Date.now() + 3 * 60_000).toISOString() },
        { id: "10", sender: "me", text: "Good night.", sentAt: new Date(Date.now() + 115 * 60_000).toISOString() },
        ],
    },
    {
      conversationId: "c2",
      partnerId: "chip-munk",
      partnerFirstName: "Chip",
      partnerLastName: "Munk",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "Donde esta la biblioteca?",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [
        { id: "m4", sender: "partner", text: "Donde esta la biblioteca?", sentAt: new Date(now - 70 * 60_000).toISOString() },
        { id: "m5", sender: "me", text: "Thanks!", sentAt: new Date(now - 68 * 60_000).toISOString() },
      ],
    },
    {
      conversationId: "c3",
      partnerId: "id",
      partnerFirstName: "Test",
      partnerLastName: "Ing",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "testing",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [],
    },
    {
      conversationId: "c4",
      partnerId: "id",
      partnerFirstName: "Test",
      partnerLastName: "Ing",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "testing",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [],
    },    
    {
      conversationId: "c5",
      partnerId: "id",
      partnerFirstName: "Test",
      partnerLastName: "Ing",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "testing",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [],
    },    
    {
      conversationId: "c6",
      partnerId: "id",
      partnerFirstName: "Test",
      partnerLastName: "Ing",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "testing",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [],
    },
        {
      conversationId: "c7",
      partnerId: "id",
      partnerFirstName: "Test",
      partnerLastName: "Ing",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "testing",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [],
    },
        {
      conversationId: "c8",
      partnerId: "id",
      partnerFirstName: "Test",
      partnerLastName: "Ing",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "testing",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [],
    },
    {
      conversationId: "c9",
      partnerId: "id",
      partnerFirstName: "Test",
      partnerLastName: "Ing",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "testing",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [],
    },
        {
      conversationId: "c10",
      partnerId: "id",
      partnerFirstName: "Test",
      partnerLastName: "Ing",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "testing",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [],
    },    {
      conversationId: "c11",
      partnerId: "id",
      partnerFirstName: "Test",
      partnerLastName: "Ing",
      partnerAvatarUrl: "/test-avatar.jpg",
      language: "Spanish",
      lastMessageText: "testing",
      lastMessageAt: new Date(now - 70 * 60_000).toISOString(),
      unreadCount: 0,
      messages: [],
    },
  ];

  return (
    <main className="h-screen overflow-hidden bg-zinc-50">
        <Chat conversations={conversations} initialConversationId="c1" />
    </main>
  );
}